name: App Pipeline Protected

on:
  push:
    branches: [ "main" ]

jobs:
  security-check:
    uses: CurrJere/TFG---Control-de-la-supply-chain/.github/workflows/secure-npm-pipeline.yml@main
    with:
      framework-repo: CurrJere/TFG---Control-de-la-supply-chain
      framework-ref: main
    permissions:
      contents: read
      security-events: write
      actions: read